import { Injectable } from '@angular/core';

export enum FormatoLocal {
    FORMATO_01 = 'Formato_01',
    FORMATO_03 = 'Formato_03',
    MANUAL_USUARIO = 'Manual_Usuario'
}

export enum Contrato {
    CONTRATO = 'Contrato'
}

export enum TipoSuspensionCancelacionEnum {
    SUSPENDIDA = 'SUSPENDIDA',
    CANCELADA = 'CANCELADA'
}

export enum NotificacionEnum {
    RESPUESTA = 'RESPUESTA',
    ARCHIVAMIENTO = 'ARCHIVAMIENTO'
}

export enum TipoPersonaEnum {
    JURIDICO = 'JURIDICO',
    NATURAL = 'NATURAL',
    PJ_EXTRANJERO = 'PJ_EXTRANJERO',
    PN_POSTOR = 'PN_POSTOR',
    PN_PERS_PROPUESTO = 'PN_PERS_PROPUESTO'
}

export enum RolEnum {
    RES_ADMIN = '01',
    RES_TECNI = '02',
    EVA_ADMIN = '03',
    EVA_TECNI = '04',

    APROB_TEC = '05',
    USU_EXTER = '06',
    APROB_ADM = '07',
    ADM_PROCE = '08',
    ADM_BLOQU = '09',
    ADM_CONFIG = '11',
    EVA_CONTRA = '12',

    INVITADO = '15',
    APROBADOR_G2='18',
    APROBADOR_G3='17',
    APROBADOR_G4='16'
}

export enum AprobadorAccion {
    APROBADO = 'APROBADO',
    RECHAZADO = 'RECHAZADO'
}

export enum EvaluadorRol {
    TECNICO = '04',
    TECNICO_ID = 102,
    TECNICO_COD = 'TECNICO',

    ADMINIS = '03',
    ADMINIS_ID = 101,
    ADMINIS_COD = 'ADMINISTRATIVO',

    APROBADOR_TECNICO = '05',
    APROBADOR_TECNICO_ID = 544,
    APROBADOR_TECNICO_COD = 'APROBADOR_TECNICO',
}

export enum SolicitudTipoEnum {
    ALL = 'ALL',
    SUBSANACION = 'SUBSANACION',
    INSCRIPCION = 'INSCRIPCION'
}

export enum SolicitudEstadoEnum {
    ALL = 'ALL',
    BORRADOR = 'BORRADOR',
    EN_PROCESO = 'EN_PROCESO',
    OBSERVADO = 'OBSERVADO',
    CONCLUIDO = 'CONCLUIDO',
    ARCHIVADO = 'ARCHIVADO'
}

export enum EstadoEvaluacionAdministrativa {
    EN_PROCESO = 'EN_PROCESO',
    EN_APROBACION = 'EN_APROBACION',
    ASIGNADO = 'ASIGNADO',
    CONCLUIDO = 'CONCLUIDO'
}

export enum EstadoProcesoEnum {
    EN_ELABORACION = 'EN_ELABORACION',
    CONVOCATORIA = 'CONVOCATORIA',
    PRESENTACION = 'PRESENTACION',
    ADMISION_CALIFICACION = 'ADMISION_CALIFICACION',
    DESIGNACION = 'DESIGNACION',
    CERRADO = 'CERRADO'
}

export enum EstadoPropuestaEnum {
    NO_PRESENTADO = 'NO_PRESENTADO',
    PRESENTADO = 'PRESENTADO'
}

export enum EstadoEvaluacionTecnica {
    EN_PROCESO = 'EN_PROCESO',
    EN_APROBACION = 'EN_APROBACION',
    ASIGNADO = 'ASIGNADO',
    CONCLUIDO = 'CONCLUIDO'
}

export enum SolicitudEstadoRevisionEnum {
    POR_ASIGNAR = 'POR_ASIGNAR',
    ASIGNADO = 'ASIGNADO',
    EN_PROCESO = 'EN_PROCESO',
    OBSERVADO = 'OBSERVADO',
    CONCLUIDO = 'CONCLUIDO',
}

export enum PerfilSesionEnum {
    USUARIO_EXTERNO     = 512,
    USUARIO_COORDINADOR = 513,
    USUARIO_EVALUADOR   = 514
}

export enum TipoDocumentoEnum {
    DNI = 'DNI',
    RUC = 'RUC',
    CARNET_EXTRA = 'CARNET_EXTRA'
}

export enum RequisitoAdjuntoEnum {
    ADJUNTO_USUARIOS = 'listado/2/detalles?size=1000',
    ADJUNTO_SOLICITUD = 'adjuntos-solicitud-acreditacion?size=1000'
}

export enum OptionEnum {
    //SOLICITUD ACREDITACION MODULO EXTERNO
    SOL_ACRE_ADD = 'SOL_ACRE_ADD',
    SOL_ACRE_EDIT = 'SOL_ACRE_EDIT',
    SOL_ACRE_VIEW = 'SOL_ACRE_VIEW',
}

export enum ListadoEnume {
    //SOLICITUD ACREDITACION MODULO EXTERNO
    AREA = 1,
}

export enum ListadoEnum {
    ESTADO_SOLICITUD = 'ESTADO_SOLICITUD',
    TIPO_DOCUMENTO = 'TIPO_DOCUMENTO',
    TIPO_DOCUMENTO_PJ = 'TIPO_DOCUMENTO_PJ',
    TIPO_CAPACITACION = 'TIPO_CAPACITACION',
    TIPO_DOCUMENTO_PN = 'TIPO_DOCUMENTO_PN',
    TIPO_CAUSALES = 'TIPO_CAUSALES',
    CAUSALES_SUSPENSION = 'CAUSALES_SUSPENSION',
    CAUSALES_CANCELACION = 'CAUSALES_CANCELACION',
    SECTOR = 'SECTOR',
    SUBSECTOR = 'SUBSECTOR',
    ACTIVIDAD = 'ACTIVIDAD',
    UNIDAD = 'UNIDAD',
    OTROS_REQUISITOS = 'OTROS_REQUISITOS',
    TIPO_DOCUMENTO_ACREDITA = 'TIPO_DOCUMENTO_ACREDITA',
    PAIS = 'PAIS',
    ESTADO_REVISION = 'ESTADO_REVISION',
    TIPO_SOLICITUD = 'TIPO_SOLICITUD',
    RESULTADO_EVALUACION = 'RESULTADO_EVALUACION',
    ESTADO_NOTIFICACION = 'ESTADO_NOTIFICACION',
    ESTADO_TOKEN = 'ESTADO_TOKEN',
    ESTADO_EVALUACION = 'ESTADO_EVALUACION',
    GRADO_ACADEMICO = 'GRADO_ACADEMICO',
    TIPO_EVALUADOR = 'TIPO_EVALUADOR',
    ESTADO_ROL = 'ESTADO_ROL',
    TIPO_ARCHIVO = 'TIPO_ARCHIVO',
    OTROS_DOCUMENTOS_PN = 'OTROS_DOCUMENTOS_PN',
    OTROS_DOCUMENTOS_PJ = 'OTROS_DOCUMENTOS_PJ',
    TIPO_ESTUDIO = 'TIPO_ESTUDIO',
    FUENTE_ESTUDIO = 'FUENTE_ESTUDIO',
    PAISES = 'PAISES',
    MONEDA = 'MONEDA',
    CUENTA_CONFORMIDAD = 'CUENTA_CONFORMIDAD',
    //UNIDAD = 'UNIDAD',
    RESULTADO_EVALUACION_ADM = 'RESULTADO_EVALUACION_ADM',
    SUBCATEGORIA = 'SUBCATEGORIA',
    PERFILES = 'PERFILES',
    RESULTADO_EVALUACION_TEC_ADM = 'RESULTADO_EVALUACION_TEC_ADM',
    GRUPOS = 'GRUPOS',
    TIPO_IDEN_TRIBUTARIA = 'TIPO_IDEN_TRIBUTARIA',
    TIPO_PERSONA = 'TIPO_PERSONA',
    CAUSAL_SUSPENSION = 'CAUSAL_SUSPENSION',
    CAUSAL_CANCELACION = 'CAUSAL_CANCELACION',

    ESTADO_PROCESO = 'ESTADO_PROCESO',
    ESTADO_ITEM = 'ESTADO_ITEM',
    ESTADO_INVITACION = 'ESTADO_INVITACION',
    ESTADO_PRESENTACION = 'ESTADO_PRESENTACION',
    ETAPA_PROCESO = 'ETAPA_PROCESO',
    CARGO_MIEMBRO = 'CARGO_MIEMBRO',
    ESTADO_SUP_PERFIL = 'ESTADO_SUP_PERFIL',

    TIPO_FACTURACION = 'TIPO_FACTURACION',
    ACTIVIDAD_AREAS = 'ACTIVIDAD_AREAS',

    TIPO_SECCION = 'TIPO_SECCION',
    TIPO_DATO = 'TIPO_DATO',
    TIPO_CONTRATO = 'TIPO_CONTRATO',
    

    TIPO_APROBACION_PERFECCIONAMIENTO = "TIPO_APROBACION_PERFECCIONAMIENTO",
    ESTADO_APROBACION_PERFECCIONAMIENTO = "ESTADO_APROBACION_PERFECCIONAMIENTO",
    TIPO_APROBACION = "TIPO_APROBACION",
    ESTADO_APROBACION_REEMP = "ESTADO_APROBACION_REEMP",

    ENTRADA_DATO = 'ENTRADA_DATO',
    ADJUDICACION_SIMPLIFICADA = 'ADJUDICACION_SIMPLIFICADA',
    CONST_ESTADO_PACE_REGISTRADO = "PACE_REG",
    CONST_ESTADO_PACE_ACTUALIZADO = "PACE_ACT",
    CONST_ESTADO_PACE_APROBADO_DIVISION = "PACE_APR_DV",
    CONST_ESTADO_PACE_OBSERVADO = "PACE_OBS",
    CONST_ESTADO_PACE_APROBADO_ENVIADO = "PACE_APR_EN",
    CONST_ESTADO_PACE_CANCELADO = "PACE_CAN",
    
}

export enum etapasProcesoEnum {
    FORMULACION_CONSULTAS = 'FORMULACIÓN DE CONSULTAS',
}

export enum solicitudContrato {
    ACCION_VER = 'ACCION_VER',
    ACCION_EDITAR = 'ACCION_EDITAR'
}

export enum reemplazoPersonalPropuesto {
    ACCION_REEMPLAZAR = 'ACCION_REEMPLAZAR',
    ACCION_REVISAR = 'ACCION_REVISAR'
}

export enum estadosIndexPerfCont {
    PRELIMINAR = '1',
    EN_PROCESO = '2',
    OBSERVADO =  '3',
    CONCLUIDO =  '4',
    ARCHIVADO =  '5'
}

export enum estadosPerfCont {
    PRELIMINAR = 'Preliminar',
    EN_PROCESO = 'En Proceso',
    OBSERVADO = 'Observado',
    CONCLUIDO = 'Concluído',
    ARCHIVADO = 'Archivado'
}

export enum tipoSolicitudPerfCont {
    INSCRIPCION = '1',
    SUBSANACION = '2'
}

@Injectable({
    providedIn: 'root'
})

export class Constantes {
    requisitoAdjunto = RequisitoAdjuntoEnum;
    tipoDocumento = TipoDocumentoEnum;
}


export enum origenRegistroEnum {
    MODIFICACION = 'MODIFICACION'
}

export enum flagEnum {
    VIGENTE = '1',
    NO_VIGENTE = '0'
}

export class UsuariosRoles{
   static GER_G2=5;
   static GER_03=5;
   static EVALUADOR=12;
   static APROBADOR_G2=18;
   static APROBADOR_G3=17;
   static APROBADOR_G4=16;

}

export class REQUERIMIENTO{
    static EVAL_INFO_APROB_G2_GER_DIV = "EVAL_INFO_APROB_G2_GER_DIV";
    static EVAL_INFO_APROB_G3_GER_LIN = "EVAL_INFO_APROB_G3_GER_LIN";
    static APROB_EVAL_CONTR = "APROB_EVAL_CONTR";
    static VB_APROB_G2_APROB_ADMIN = "VB_APROB_G2_APROB_ADMIN";
    static FIRMA_APROB_G3_APROB_ADMIN = "FIRMA_APROB_G3_APROB_ADMIN";
    static APROB_ADMIN_G4_GAF = "APROB_ADMIN_G4_GAF";
    static EVAL_DOC_EVAL_TEC_CONT  = "EVAL_DOC_EVAL_TEC_CONT";
    static  EVAL_INF_APROB_TEC_G2  = "EVAL_INF_APROB_TEC_G2";
    static  EVAL_INF_APROB_TEC_G3  = "EVAL_INF_APROB_TEC_G3";

	}