name: Build and Analyze (SonarQube)

on:
  workflow_dispatch:
  push:
    branches:
      - develop-1709-sonar

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (for Angular projects)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up Java (required by SonarQube scanner)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=PRUEBA-FRONT
            -Dsonar.projectName="PRUEBA-FRONT"
            -Dsonar.sources=src
            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
